### ISSUE TITLE
Error -o and google dorks

### ISSUE THREAD

**Issue by lolminerxmrig** [securekomodo/citrixInspector#1]
hi not work -o outfile.
python cve_2023_3519_inspector.py -u <target_url> -o <output_file>

python3 cve_2023_3519_inspector.py --file 1.txt -o 2.txt

plz add google dorks.

**Comment by securekomodo** [comment]
Readme had an incorrect command example. I have updated it to reflect current command params. Please use the following format:
```
python cve_2023_3519_inspector.py -u <target url> -l <log-file>
```

You can also check help with
```
python cve_2023_3519_inspector.py -h
```
